#自動調用api保活
name: Auto Api

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 */5 * * *
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安裝python
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install requests #安裝requests
      run: |
        pip install requests
    - name: Test Api #Api調用
      env: 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CONFIG_KEY }}
      run: |
        python ApiSecret.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    
    - name: commit #重新上傳新token
      run: |
        git config --global user.email galande5@outlook.com
        git config --global user.name galande5
        git add .
        git commit -m "update new token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
